# Generated by Django 3.2.4 on 2021-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
