# Generated by Django 3.2.4 on 2021-07-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210727_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='imgs',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='icecreams',
            field=models.ManyToManyField(default='none', to='main_app.IceCream'),
        ),
    ]
